name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign reviewer
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto-assign-config.yml
