name: Gemini AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  gemini-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Gemini AI Code Review
        uses: DamianReeves/gemini-ai-reviewer@v0.1.0
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ''  # Not needed for Gemini
          review-comment-lgtm: true  # Add a comment even when no issues are found
      
      - name: Auto Approve PR if Gemini Review Passes
        if: success()
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
